
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    USE testdb;
    CREATE TABLE IF NOT EXISTS cliente (
      id INT AUTO_INCREMENT PRIMARY KEY,
      nombre VARCHAR(100),
      correo VARCHAR(100),
      telefono VARCHAR(15)
    );
